--6.1
SELECT EXTRACT(YEAR FROM ORDERDATE) AS "Year", 
    COUNT(ORDERID) AS "Total"
FROM ORDERS 
    GROUP BY EXTRACT(YEAR FROM ORDERDATE)
    
SELECT COUNT(ORDERID)
FROM ORDERS 
    
--6.2
SELECT (
    SELECT LASTNAME||' '||FIRSTNAME 
    FROM EMPLOYEES 
        WHERE EMPLOYEES.EMPLOYEEID=ORDERS.EMPLOYEEID) 
    AS "Seller",
    COUNT(ORDERID) AS "Amount"
FROM ORDERS 
    GROUP BY EMPLOYEEID
    ORDER BY COUNT(ORDERID) DESC
    
--6.3
SELECT COUNTRY,
    COUNT(CUSTOMERID) AS "Count"
FROM CUSTOMERS 
    GROUP BY COUNTRY
    ORDER BY COUNT(CUSTOMERID) DESC
    FETCH FIRST 5 ROWS ONLY;
    
--6.4
SELECT 
    CASE GROUPING(EMPLOYEEID) 
        WHEN 1
            THEN 'ALL' 
        ELSE (
            SELECT LASTNAME||' '||FIRSTNAME 
            FROM EMPLOYEES 
                WHERE EMPLOYEES.EMPLOYEEID=ORDERS.EMPLOYEEID) 
    END AS Seller,
    CASE GROUPING(CUSTOMERID)
        WHEN 1
            THEN 'ALL' 
        ELSE (
            SELECT CONTACTNAME
            FROM CUSTOMERS 
                WHERE CUSTOMERS.CUSTOMERID=ORDERS.CUSTOMERID) 
    END AS Customer,
    COUNT(ORDERID) AS Amount
FROM ORDERS
    WHERE  EXTRACT(YEAR FROM ORDERDATE) = '1998'
    GROUP BY 
        CUBE (EMPLOYEEID, CUSTOMERID)
    ORDER BY GROUPING(CUSTOMERID) DESC,
             GROUPING(EMPLOYEEID) DESC,
             Seller, Customer, Amount DESC
             
--6.5
SELECT 
    CONTACTNAME AS Person,
    'Customer' AS "Type",
    CITY AS City
FROM CUSTOMERS
    WHERE CITY IN (SELECT CITY FROM EMPLOYEES)
    GROUP BY 
        CITY, CONTACTNAME
UNION
SELECT 
    LASTNAME||' '||FIRSTNAME  AS Person,
    'Seller' AS "Type",
    CITY AS City
FROM EMPLOYEES
    WHERE CITY IN (SELECT CITY FROM CUSTOMERS)
    GROUP BY 
        CITY, LASTNAME||' '||FIRSTNAME
    ORDER BY City, Person
    
--6.6
SELECT DISTINCT t1.CUSTOMERID, t1.CITY
FROM CUSTOMERS t1
    JOIN CUSTOMERS t2
        ON t2.CITY=t1.CITY
    WHERE t2.CUSTOMERID<>t1.CUSTOMERID
    ORDER BY CITY

SELECT CITY, COUNT(CUSTOMERID)
FROM CUSTOMERS
    GROUP BY CITY
    HAVING COUNT(CUSTOMERID)>1
    
--6.7
SELECT DISTINCT t1.LASTNAME AS "User name",
    t2.LASTNAME AS "Boss"
FROM EMPLOYEES t1
    JOIN EMPLOYEES t2
        ON t2.EMPLOYEEID=t1.REPORTSTO
    