--7.1
SELECT LASTNAME,TERRITORYDESCRIPTION
FROM EMPLOYEES
    JOIN EMPLOYEETERRITORIES
        ON EMPLOYEES.EMPLOYEEID=EMPLOYEETERRITORIES.EMPLOYEEID
    JOIN TERRITORIES
        ON EMPLOYEETERRITORIES.TERRITORYID=TERRITORIES.TERRITORYID
    WHERE TERRITORIES.REGIONID=2