--5.1
SELECT
    TO_CHAR(SUM(UNITPRICE*QUANTITY*(1-DISCOUNT)), '$999,999,999,999.99') AS "Totals"
FROM ORDER_DETAILS

--5.2
SELECT
    COUNT(*)-COUNT(SHIPPEDDATE) AS "Not shipped count"
FROM ORDERS

--5.3
SELECT 
    COUNT(DISTINCT CUSTOMERID) AS "Customers count"
FROM ORDERS
   